// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/eufelipemateus/go-github-stats/frontend/models"
)

func newRepository(db *gorm.DB, opts ...gen.DOOption) repository {
	_repository := repository{}

	_repository.repositoryDo.UseDB(db, opts...)
	_repository.repositoryDo.UseModel(&models.Repository{})

	tableName := _repository.repositoryDo.TableName()
	_repository.ALL = field.NewAsterisk(tableName)
	_repository.ID = field.NewUint(tableName, "id")
	_repository.CreatedAt = field.NewTime(tableName, "created_at")
	_repository.UpdatedAt = field.NewTime(tableName, "updated_at")
	_repository.Name = field.NewString(tableName, "name")
	_repository.CountStars = field.NewInt(tableName, "count_stars")
	_repository.CountForks = field.NewInt(tableName, "count_forks")
	_repository.CollectID = field.NewUint(tableName, "collect_id")
	_repository.Collect = repositoryBelongsToCollect{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Collect", "models.Collect"),
		User: struct {
			field.RelationField
			Following struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Collect.User", "models.User"),
			Following: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Collect.User.Following", "models.Collect"),
			},
		},
		Followers: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Collect.Followers", "models.User"),
		},
	}

	_repository.fillFieldMap()

	return _repository
}

type repository struct {
	repositoryDo

	ALL        field.Asterisk
	ID         field.Uint
	CreatedAt  field.Time
	UpdatedAt  field.Time
	Name       field.String
	CountStars field.Int
	CountForks field.Int
	CollectID  field.Uint
	Collect    repositoryBelongsToCollect

	fieldMap map[string]field.Expr
}

func (r repository) Table(newTableName string) *repository {
	r.repositoryDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r repository) As(alias string) *repository {
	r.repositoryDo.DO = *(r.repositoryDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *repository) updateTableName(table string) *repository {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint(table, "id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.Name = field.NewString(table, "name")
	r.CountStars = field.NewInt(table, "count_stars")
	r.CountForks = field.NewInt(table, "count_forks")
	r.CollectID = field.NewUint(table, "collect_id")

	r.fillFieldMap()

	return r
}

func (r *repository) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *repository) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 8)
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["name"] = r.Name
	r.fieldMap["count_stars"] = r.CountStars
	r.fieldMap["count_forks"] = r.CountForks
	r.fieldMap["collect_id"] = r.CollectID

}

func (r repository) clone(db *gorm.DB) repository {
	r.repositoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r repository) replaceDB(db *gorm.DB) repository {
	r.repositoryDo.ReplaceDB(db)
	return r
}

type repositoryBelongsToCollect struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
		Following struct {
			field.RelationField
		}
	}
	Followers struct {
		field.RelationField
	}
}

func (a repositoryBelongsToCollect) Where(conds ...field.Expr) *repositoryBelongsToCollect {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a repositoryBelongsToCollect) WithContext(ctx context.Context) *repositoryBelongsToCollect {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a repositoryBelongsToCollect) Model(m *models.Repository) *repositoryBelongsToCollectTx {
	return &repositoryBelongsToCollectTx{a.db.Model(m).Association(a.Name())}
}

type repositoryBelongsToCollectTx struct{ tx *gorm.Association }

func (a repositoryBelongsToCollectTx) Find() (result *models.Collect, err error) {
	return result, a.tx.Find(&result)
}

func (a repositoryBelongsToCollectTx) Append(values ...*models.Collect) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a repositoryBelongsToCollectTx) Replace(values ...*models.Collect) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a repositoryBelongsToCollectTx) Delete(values ...*models.Collect) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a repositoryBelongsToCollectTx) Clear() error {
	return a.tx.Clear()
}

func (a repositoryBelongsToCollectTx) Count() int64 {
	return a.tx.Count()
}

type repositoryDo struct{ gen.DO }

type IRepositoryDo interface {
	gen.SubQuery
	Debug() IRepositoryDo
	WithContext(ctx context.Context) IRepositoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRepositoryDo
	WriteDB() IRepositoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRepositoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRepositoryDo
	Not(conds ...gen.Condition) IRepositoryDo
	Or(conds ...gen.Condition) IRepositoryDo
	Select(conds ...field.Expr) IRepositoryDo
	Where(conds ...gen.Condition) IRepositoryDo
	Order(conds ...field.Expr) IRepositoryDo
	Distinct(cols ...field.Expr) IRepositoryDo
	Omit(cols ...field.Expr) IRepositoryDo
	Join(table schema.Tabler, on ...field.Expr) IRepositoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRepositoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRepositoryDo
	Group(cols ...field.Expr) IRepositoryDo
	Having(conds ...gen.Condition) IRepositoryDo
	Limit(limit int) IRepositoryDo
	Offset(offset int) IRepositoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRepositoryDo
	Unscoped() IRepositoryDo
	Create(values ...*models.Repository) error
	CreateInBatches(values []*models.Repository, batchSize int) error
	Save(values ...*models.Repository) error
	First() (*models.Repository, error)
	Take() (*models.Repository, error)
	Last() (*models.Repository, error)
	Find() ([]*models.Repository, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Repository, err error)
	FindInBatches(result *[]*models.Repository, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Repository) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRepositoryDo
	Assign(attrs ...field.AssignExpr) IRepositoryDo
	Joins(fields ...field.RelationField) IRepositoryDo
	Preload(fields ...field.RelationField) IRepositoryDo
	FirstOrInit() (*models.Repository, error)
	FirstOrCreate() (*models.Repository, error)
	FindByPage(offset int, limit int) (result []*models.Repository, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRepositoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r repositoryDo) Debug() IRepositoryDo {
	return r.withDO(r.DO.Debug())
}

func (r repositoryDo) WithContext(ctx context.Context) IRepositoryDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r repositoryDo) ReadDB() IRepositoryDo {
	return r.Clauses(dbresolver.Read)
}

func (r repositoryDo) WriteDB() IRepositoryDo {
	return r.Clauses(dbresolver.Write)
}

func (r repositoryDo) Session(config *gorm.Session) IRepositoryDo {
	return r.withDO(r.DO.Session(config))
}

func (r repositoryDo) Clauses(conds ...clause.Expression) IRepositoryDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r repositoryDo) Returning(value interface{}, columns ...string) IRepositoryDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r repositoryDo) Not(conds ...gen.Condition) IRepositoryDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r repositoryDo) Or(conds ...gen.Condition) IRepositoryDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r repositoryDo) Select(conds ...field.Expr) IRepositoryDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r repositoryDo) Where(conds ...gen.Condition) IRepositoryDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r repositoryDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IRepositoryDo {
	return r.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (r repositoryDo) Order(conds ...field.Expr) IRepositoryDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r repositoryDo) Distinct(cols ...field.Expr) IRepositoryDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r repositoryDo) Omit(cols ...field.Expr) IRepositoryDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r repositoryDo) Join(table schema.Tabler, on ...field.Expr) IRepositoryDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r repositoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRepositoryDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r repositoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IRepositoryDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r repositoryDo) Group(cols ...field.Expr) IRepositoryDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r repositoryDo) Having(conds ...gen.Condition) IRepositoryDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r repositoryDo) Limit(limit int) IRepositoryDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r repositoryDo) Offset(offset int) IRepositoryDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r repositoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRepositoryDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r repositoryDo) Unscoped() IRepositoryDo {
	return r.withDO(r.DO.Unscoped())
}

func (r repositoryDo) Create(values ...*models.Repository) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r repositoryDo) CreateInBatches(values []*models.Repository, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r repositoryDo) Save(values ...*models.Repository) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r repositoryDo) First() (*models.Repository, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Repository), nil
	}
}

func (r repositoryDo) Take() (*models.Repository, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Repository), nil
	}
}

func (r repositoryDo) Last() (*models.Repository, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Repository), nil
	}
}

func (r repositoryDo) Find() ([]*models.Repository, error) {
	result, err := r.DO.Find()
	return result.([]*models.Repository), err
}

func (r repositoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Repository, err error) {
	buf := make([]*models.Repository, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r repositoryDo) FindInBatches(result *[]*models.Repository, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r repositoryDo) Attrs(attrs ...field.AssignExpr) IRepositoryDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r repositoryDo) Assign(attrs ...field.AssignExpr) IRepositoryDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r repositoryDo) Joins(fields ...field.RelationField) IRepositoryDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r repositoryDo) Preload(fields ...field.RelationField) IRepositoryDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r repositoryDo) FirstOrInit() (*models.Repository, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Repository), nil
	}
}

func (r repositoryDo) FirstOrCreate() (*models.Repository, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Repository), nil
	}
}

func (r repositoryDo) FindByPage(offset int, limit int) (result []*models.Repository, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r repositoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r repositoryDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r repositoryDo) Delete(models ...*models.Repository) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *repositoryDo) withDO(do gen.Dao) *repositoryDo {
	r.DO = *do.(*gen.DO)
	return r
}
